### ISSUE TITLE
404 page

### ISSUE THREAD

**Issue by mkozhukharenko** [mkozhukharenko/ums-frontend#31]
### create 404 page
- [x] Create route for 404 (path="404'")
  Note: there are already a redirect present. 
  `<Redirect from='*' to='/404'/>`
- [x] Create a Component 
  component should have 'Сторінка не знайдена' sign and should have link to the main page (smth like "Перейти на гловну сторінку" )

Expected result:

If user enter a route and there no such route in the application - he should get a '404' page

**Comment by ghost** [comment]
Create PageNotFound component
