### ISSUE TITLE
Показувати  gender statistics

### ISSUE THREAD

**Issue by ivanursul** [mkozhukharenko/ums-frontend#38]
Показувати в вигляді pie-chart інформацію про гендерний розподіл - скільки хлопців і скільки дівчат

[GET] `api/stats/{timePeriodId}/specoffers/{specoffersId}/genders`

**Comment by mkozhukharenko** [comment]
a wireframe: 

![image](https://cloud.githubusercontent.com/assets/9365923/14852904/c2f4235e-0c91-11e6-8361-af6b3b54fd05.png)
